# Generated by Django 4.1.1 on 2022-09-10 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_transaction_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='direction',
            field=models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], default='debit', max_length=6),
        ),
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('dst_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_advance', to=settings.AUTH_USER_MODEL)),
                ('src_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_advance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
